version: '3'
services:
  preconf_bot:
    build: .
    networks:
      - app-network
    environment:
      - PRIVATE_KEY=${PRIVATE_KEY}
      - RPC_ENDPOINT=${RPC_ENDPOINT}
      - WS_ENDPOINT=${WS_ENDPOINT}
      - USE_PAYLOAD=${USE_PAYLOAD}
      - SERVER_ADDRESS=${SERVER_ADDRESS}
      - OFFSET=${OFFSET}
      - NUM_BLOB=${NUM_BLOB}
      - BID_AMOUNT=${BID_AMOUNT}
      - BID_AMOUNT_STD_DEV_PERCENTAGE=${BID_AMOUNT_STD_DEV_PERCENTAGE}
      - DEFAULT_TIMEOUT=${DEFAULT_TIMEOUT}
      - APP_NAME=${APP_NAME}
      - VERSION=${VERSION}
networks:
  app-network:
    external: true
